import type { Product } from "./types";
import { PDF_CATALOG_PRODUCTS } from "./pdf-extracted-products";

const BASE_PRODUCTS: Product[] = [
  {
    slug: "mola-barra-olimpica",
    name: "Mola para Barra Olímpica",
    shortName: "Mola Barra Olímpica",
    category: "academia",
    categoryLabel: "Molas para Academia",
    ref: "INC-ACM-001",
    price: 34.9,
    unitLabel: "por par · à vista no pix",
    spec: "ø 45mm · ø arame 4,5mm · L 115mm · SAE 9254",
    description: [
      "A Mola para Barra Olímpica Incomolas é fabricada em aço SAE 9254 de alta resistência, com tratamento de fosfato preto para proteção contra oxidação e melhor retenção de lubrificantes. Desenvolvida para barras de 45mm de diâmetro, padrão olímpico.",
      "Cada par passa por inspeção dimensional e de carga antes do envio. A constante de mola de 8,4 kgf/mm garante acionamento seguro e suave, com longa vida útil mesmo em uso intenso em academias.",
      "Disponível em acabamentos zinco, cromo e natural para aplicações específicas. Para pedidos de grande volume ou especificações fora do padrão, entre em contato com nossa equipe técnica.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254", "Aço Carbono", "Inox AISI 304"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Zinco", "Cromo", "Natural"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado disponível" },
      { kind: "par", label: "Vendido em Par" },
    ],
    rating: 4.0,
    ratingCount: 38,
    bulk: [
      { qty: "1–9 pares", price: "R$ 34,90" },
      { qty: "10–49 pares", price: "R$ 29,90", save: "–14%" },
      { qty: "50–199 pares", price: "R$ 24,90", save: "–29%" },
      { qty: "200+ pares", price: "Consulte" },
    ],
    imageTone: "steel",
    image: "/products/mola-academia.png",
    diameterWire: 4.5,
    specs: {
      dimensoes: [
        { key: "Diâmetro externo", value: "45 mm" },
        { key: "Diâmetro do arame", value: "4,5 mm" },
        { key: "Comprimento livre", value: "115 mm" },
        { key: "Comprimento sólido", value: "54 mm" },
        { key: "Número de espiras ativas", value: "11" },
        { key: "Número de espiras totais", value: "13" },
        { key: "Passo", value: "5,5 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Acabamento padrão", value: "Fosfato preto" },
        { key: "Constante de mola (k)", value: "8,4 kgf/mm" },
        { key: "Carga de trabalho máx.", value: "120 kgf" },
        { key: "Deflexão máx. (trabalho)", value: "61 mm" },
        { key: "Sentido de enrolamento", value: "Dextrorso" },
        { key: "Extremidades", value: "Fechadas e retificadas" },
      ],
    },
  },
  {
    slug: "mola-barra-curta",
    name: "Mola Barra Curta",
    category: "academia",
    categoryLabel: "Molas para Academia",
    ref: "INC-ACM-002",
    price: 28.5,
    unitLabel: "por par",
    spec: "ø 38mm · ø arame 4mm · L 95mm · SAE 9254",
    description: [
      "Mola compacta para barras curtas de musculação. Aço SAE 9254 com tratamento anticorrosivo.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254", "Aço Carbono"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Zinco"],
    disponibilidade: ["estoque"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "par", label: "Par" },
    ],
    rating: 4.5,
    ratingCount: 22,
    bulk: [
      { qty: "1–9 pares", price: "R$ 28,50" },
      { qty: "10+ pares", price: "R$ 24,90", save: "–13%" },
    ],
    imageTone: "steel",
    image: "/products/mola-academia.png",
    diameterWire: 4,
    specs: {
      dimensoes: [
        { key: "Diâmetro externo", value: "38 mm" },
        { key: "Diâmetro do arame", value: "4,0 mm" },
        { key: "Comprimento livre", value: "95 mm" },
        { key: "Espiras totais", value: "11" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Carga máx.", value: "85 kgf" },
        { key: "Constante k", value: "6,2 kgf/mm" },
      ],
    },
  },
  {
    slug: "mola-leg-press",
    name: "Mola Leg Press",
    category: "academia",
    categoryLabel: "Molas para Academia",
    ref: "INC-ACM-007",
    price: 68.0,
    unitLabel: "unidade",
    spec: "ø 60mm · ø arame 6mm · L 200mm · Cromo",
    description: [
      "Mola robusta para equipamentos Leg Press. Acabamento cromado, alta durabilidade.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254", "Aço Especial"],
    acabamento: "Cromo",
    acabamentos: ["Cromo", "Zinco"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 5,
    ratingCount: 12,
    bulk: [
      { qty: "1–4 un", price: "R$ 68,00" },
      { qty: "5–19 un", price: "R$ 59,00", save: "–13%" },
      { qty: "20+ un", price: "Consulte" },
    ],
    imageTone: "chrome",
    image: "/products/mola-academia.png",
    diameterWire: 6,
    specs: {
      dimensoes: [
        { key: "Diâmetro externo", value: "60 mm" },
        { key: "Diâmetro do arame", value: "6,0 mm" },
        { key: "Comprimento livre", value: "200 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Acabamento", value: "Cromo industrial" },
        { key: "Carga máx.", value: "240 kgf" },
      ],
    },
  },
  {
    slug: "mola-haltere-20kg",
    name: "Mola Haltere 20kg",
    category: "academia",
    categoryLabel: "Molas para Academia",
    ref: "INC-ACM-014",
    price: 42.0,
    unitLabel: "por par",
    spec: "ø 50mm · ø arame 5mm · L 80mm · Cromo",
    description: ["Mola de retenção para halteres profissionais até 20kg."],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Cromo",
    acabamentos: ["Cromo"],
    disponibilidade: ["estoque"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "par", label: "Par" },
    ],
    rating: 4.2,
    ratingCount: 19,
    bulk: [{ qty: "1+ pares", price: "R$ 42,00" }],
    imageTone: "chrome",
    image: "/products/mola-academia.png",
    diameterWire: 5,
    specs: {
      dimensoes: [
        { key: "Diâmetro externo", value: "50 mm" },
        { key: "Diâmetro do arame", value: "5,0 mm" },
        { key: "Comprimento livre", value: "80 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Carga máx.", value: "20 kg" },
      ],
    },
  },
  {
    slug: "kit-molas-cama-4-5m",
    name: "Kit Molas Cama 4,5m",
    shortName: "Kit Molas 4,5m",
    category: "cama",
    categoryLabel: "Cama Elástica",
    ref: "INC-CAM-072",
    price: 189.0,
    unitLabel: "kit 72 unidades",
    spec: "ø 5mm · L 180mm · Zinco · Kit 72 unidades",
    description: [
      "Kit completo com 72 molas zincadas para cama elástica de 4,5m de diâmetro. Tratamento anticorrosivo para uso externo.",
    ],
    material: "Aço Carbono",
    materials: ["Aço Carbono", "Aço SAE 9254"],
    acabamento: "Zinco",
    acabamentos: ["Zinco", "Cromo"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "kit", label: "Kit 72un" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 54,
    bulk: [
      { qty: "1 kit", price: "R$ 189,00" },
      { qty: "5+ kits", price: "R$ 165,00", save: "–13%" },
      { qty: "20+ kits", price: "Consulte" },
    ],
    imageTone: "zinc",
    image: "/products/mola-cama-elastica.png",
    diameterWire: 5,
    specs: {
      dimensoes: [
        { key: "Diâmetro do arame", value: "5,0 mm" },
        { key: "Comprimento livre", value: "180 mm" },
        { key: "Quantidade no kit", value: "72 unidades" },
      ],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Acabamento", value: "Zincado" },
        { key: "Diâmetro da cama", value: "4,5 m" },
      ],
    },
  },
  {
    slug: "kit-molas-cama-4m",
    name: "Kit Molas Cama 4m",
    shortName: "Kit Molas 4m",
    category: "cama",
    categoryLabel: "Cama Elástica",
    ref: "INC-CAM-060",
    price: 149.0,
    unitLabel: "kit 60 unidades",
    spec: "ø 5mm · L 160mm · Zinco · Kit 60 unidades",
    description: ["Kit com 60 molas zincadas para camas elásticas de 4m."],
    material: "Aço Carbono",
    materials: ["Aço Carbono"],
    acabamento: "Zinco",
    acabamentos: ["Zinco"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "kit", label: "Kit 60un" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.6,
    ratingCount: 38,
    bulk: [
      { qty: "1 kit", price: "R$ 149,00" },
      { qty: "5+ kits", price: "R$ 132,00", save: "–11%" },
    ],
    imageTone: "zinc",
    image: "/products/mola-cama-elastica.png",
    diameterWire: 5,
    specs: {
      dimensoes: [
        { key: "Diâmetro do arame", value: "5,0 mm" },
        { key: "Comprimento livre", value: "160 mm" },
        { key: "Quantidade no kit", value: "60 unidades" },
      ],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Acabamento", value: "Zincado" },
        { key: "Diâmetro da cama", value: "4,0 m" },
      ],
    },
  },
  {
    slug: "mola-jump-profissional",
    name: "Mola Jump Profissional",
    shortName: "Mola Jump Pro",
    category: "jump",
    categoryLabel: "Jump / Mini Cama",
    ref: "INC-JMP-004",
    price: 8.9,
    unitLabel: "unidade",
    spec: "ø arame 4mm · L 140mm · Inox AISI 304",
    description: [
      "Mola em aço inox para jumps profissionais. Resistente à corrosão para uso em academias.",
    ],
    material: "Inox AISI 304",
    materials: ["Inox AISI 304", "Aço SAE 9254"],
    acabamento: "Natural",
    acabamentos: ["Natural"],
    disponibilidade: ["sobmedida", "atacado"],
    badges: [
      { kind: "sobmedida", label: "Sob Medida" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.8,
    ratingCount: 91,
    bulk: [
      { qty: "1–35 un", price: "R$ 8,90" },
      { qty: "36–143 un", price: "R$ 7,50", save: "–16%" },
      { qty: "144+ un", price: "Consulte" },
    ],
    imageTone: "green",
    image: "/products/mola-jump.png",
    diameterWire: 4,
    specs: {
      dimensoes: [
        { key: "Diâmetro do arame", value: "4,0 mm" },
        { key: "Comprimento livre", value: "140 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Inox AISI 304" },
        { key: "Aplicação", value: "Jump profissional" },
      ],
    },
  },
  {
    slug: "mola-compressao-industrial",
    name: "Mola Compressão Industrial",
    shortName: "Mola Compressão",
    category: "industrial",
    categoryLabel: "Industrial",
    ref: "INC-IND-022",
    price: 18.5,
    unitLabel: "unidade",
    spec: "ø 80mm · ø arame 12mm · L 300mm · Especial",
    description: [
      "Mola pesada para aplicações industriais de compressão. Sob consulta para especificações personalizadas.",
    ],
    material: "Aço Especial",
    materials: ["Aço Especial", "Aço SAE 9254"],
    acabamento: "Natural",
    acabamentos: ["Natural", "Fosfato Preto"],
    disponibilidade: ["sobmedida"],
    badges: [
      { kind: "consulte", label: "Consulte" },
      { kind: "sobmedida", label: "Sob Medida" },
    ],
    rating: 4.9,
    ratingCount: 8,
    bulk: [{ qty: "Lote mínimo", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-industrial.png",
    diameterWire: 12,
    specs: {
      dimensoes: [
        { key: "Diâmetro externo", value: "80 mm" },
        { key: "Diâmetro do arame", value: "12,0 mm" },
        { key: "Comprimento livre", value: "300 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço Especial" },
        { key: "Aplicação", value: "Compressão industrial" },
      ],
    },
  },
  {
    slug: "mola-suspensao-carro",
    name: "Mola Suspensão — Veículo Leve",
    shortName: "Mola Suspensão Carro",
    category: "automotivo",
    categoryLabel: "Automotivo",
    ref: "INC-AUT-101",
    price: 145.0,
    unitLabel: "unidade",
    spec: "ø 110mm · ø arame 12mm · L 350mm · SAE 9254",
    description: [
      "Mola helicoidal de suspensão para veículos de passeio. Fabricada em aço SAE 9254 com tratamento térmico controlado para garantir resposta consistente em qualquer terreno.",
      "Disponível para aplicações originais ou rebaixadas. Para projetos especiais (kits sport, off-road, lift), envie a especificação completa para nossa engenharia.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254", "Aço Especial"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Zinco"],
    disponibilidade: ["estoque", "atacado", "sobmedida"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 26,
    bulk: [
      { qty: "1–3 un", price: "R$ 145,00" },
      { qty: "4–11 un", price: "R$ 129,00", save: "–11%" },
      { qty: "12+ un", price: "Consulte" },
    ],
    imageTone: "dark",
    image: "/products/mola-carros.png",
    diameterWire: 12,
    specs: {
      dimensoes: [
        { key: "Diâmetro externo", value: "110 mm" },
        { key: "Diâmetro do arame", value: "12,0 mm" },
        { key: "Comprimento livre", value: "350 mm" },
        { key: "Espiras totais", value: "8" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Carga máx.", value: "780 kgf" },
        { key: "Constante k", value: "23,4 kgf/mm" },
      ],
    },
  },
  {
    slug: "mola-suspensao-caminhao",
    name: "Mola Suspensão — Caminhão",
    shortName: "Mola Caminhão",
    category: "automotivo",
    categoryLabel: "Automotivo",
    ref: "INC-AUT-220",
    price: 320.0,
    unitLabel: "unidade",
    spec: "ø 160mm · ø arame 22mm · L 480mm · Aço Especial",
    description: [
      "Mola helicoidal de alta capacidade para caminhões e veículos pesados. Resistência reforçada para cargas elevadas e uso contínuo.",
      "Atendemos frotistas, oficinas e fabricantes com lotes a partir de 10 unidades. Especificações sob medida para projetos OEM.",
    ],
    material: "Aço Especial",
    materials: ["Aço Especial", "Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Natural"],
    disponibilidade: ["atacado", "sobmedida"],
    badges: [
      { kind: "atacado", label: "Atacado" },
      { kind: "sobmedida", label: "Sob Medida" },
    ],
    rating: 4.9,
    ratingCount: 14,
    bulk: [
      { qty: "1–9 un", price: "R$ 320,00" },
      { qty: "10–49 un", price: "R$ 285,00", save: "–11%" },
      { qty: "50+ un", price: "Consulte" },
    ],
    imageTone: "dark",
    image: "/products/mola-caminhao.png",
    diameterWire: 22,
    specs: {
      dimensoes: [
        { key: "Diâmetro externo", value: "160 mm" },
        { key: "Diâmetro do arame", value: "22,0 mm" },
        { key: "Comprimento livre", value: "480 mm" },
        { key: "Espiras totais", value: "7" },
      ],
      desempenho: [
        { key: "Material", value: "Aço Especial" },
        { key: "Carga máx.", value: "2.100 kgf" },
        { key: "Constante k", value: "62,0 kgf/mm" },
        { key: "Aplicação", value: "Suspensão veículo pesado" },
      ],
    },
  },
  {
    slug: "mola-sob-medida",
    name: "Mola Sob Medida",
    category: "industrial",
    categoryLabel: "Industrial",
    ref: "INC-CUST-000",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "projeto especial",
    spec: "Qualquer diâmetro · Qualquer comprimento · Qualquer material",
    description: [
      "Projeto sob medida para sua aplicação. Envie suas especificações e receba um orçamento técnico em até 24h.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254", "Aço Carbono", "Inox AISI 304", "Aço Especial"],
    acabamento: "Natural",
    acabamentos: ["Natural", "Fosfato Preto", "Zinco", "Cromo"],
    disponibilidade: ["sobmedida"],
    badges: [{ kind: "sobmedida", label: "Projeto especial" }],
    rating: 5,
    ratingCount: 4,
    bulk: [{ qty: "Sob projeto", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-customizada.png",
    diameterWire: 0,
    specs: {
      dimensoes: [{ key: "Configuração", value: "Sob projeto" }],
      desempenho: [
        { key: "Prazo de orçamento", value: "Até 24h" },
        { key: "Documento exigido", value: "Desenho técnico ou amostra" },
      ],
    },
  },

  // ============================================================
  // LINHA AGRÍCOLA — Catálogo Incomolas de Molas Agrícolas
  // Molas BALDAN, MONTANA, TATU, JUMIL, SEMEATO, MASSEY FERGUSON,
  // NEW HOLLAND, JACTO, SLC, IDEAL, NOGUEIRA, MENEGAS
  // ============================================================

  // ---------- BALDAN ----------
  {
    slug: "mola-baldan-plantadeira-pst",
    name: "Mola Plantadeira Baldan PST/PSM",
    shortName: "Mola Baldan PST",
    category: "agricola",
    categoryLabel: "Agrícola · Baldan",
    ref: "60.20.15.03.578",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Plantadeira Baldan · Pressão da linha · Aço SAE 9254",
    description: [
      "Mola de pressão da linha de plantio para plantadeiras Baldan PST e PSM. Garante carga constante sobre o sulcador, mantendo profundidade de semeadura uniforme em diferentes condições de solo.",
      "Reposição direta do código original Baldan. Disponível em estoque e em lotes para revendedores e oficinas agrícolas.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254", "Aço Carbono"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Zinco"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
      { kind: "neutro", label: "Original Baldan" },
    ],
    rating: 4.8,
    ratingCount: 47,
    bulk: [
      { qty: "1–9 un", price: "Consulte" },
      { qty: "10+ un", price: "Atacado" },
    ],
    imageTone: "dark",
    image: "/products/mola-industrial.png",
    diameterWire: 6,
    specs: {
      dimensoes: [
        { key: "Diâmetro do arame", value: "6,0 mm" },
        { key: "Aplicação", value: "Plantadeira Baldan PST/PSM" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Função", value: "Pressão da linha de plantio" },
      ],
    },
  },
  {
    slug: "mola-baldan-grade-niveladora",
    name: "Mola Grade Niveladora Baldan",
    shortName: "Mola Baldan Grade",
    category: "agricola",
    categoryLabel: "Agrícola · Baldan",
    ref: "60.20.15.03.770",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Grade Baldan · Articulação · Aço Especial",
    description: [
      "Mola robusta para grades niveladoras e aradoras Baldan. Atua nas articulações dos discos, absorvendo impactos e protegendo o conjunto contra obstáculos no solo.",
    ],
    material: "Aço Especial",
    materials: ["Aço Especial", "Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Natural"],
    disponibilidade: ["estoque", "atacado", "sobmedida"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 22,
    bulk: [
      { qty: "1–4 un", price: "Consulte" },
      { qty: "5+ un", price: "Atacado" },
    ],
    imageTone: "dark",
    image: "/products/mola-industrial.png",
    diameterWire: 8,
    specs: {
      dimensoes: [
        { key: "Diâmetro do arame", value: "8,0 mm" },
        { key: "Aplicação", value: "Grade niveladora Baldan" },
      ],
      desempenho: [
        { key: "Material", value: "Aço Especial" },
        { key: "Função", value: "Articulação de discos" },
      ],
    },
  },

  // ---------- MONTANA ----------
  {
    slug: "mola-montana-subsolador",
    name: "Mola Subsolador Montana",
    shortName: "Mola Montana Subsolador",
    category: "agricola",
    categoryLabel: "Agrícola · Montana",
    ref: "466.728",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Subsolador Montana · Haste de proteção · SAE 9254",
    description: [
      "Mola de proteção da haste para subsoladores Montana. Permite recuo da haste em caso de impacto com pedras ou obstáculos, evitando danos estruturais ao implemento.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.6,
    ratingCount: 14,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-industrial.png",
    diameterWire: 9,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "9,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Função", value: "Proteção da haste" },
      ],
    },
  },
  {
    slug: "mola-montana-plantadeira",
    name: "Mola Plantadeira Montana",
    shortName: "Mola Montana Plant.",
    category: "agricola",
    categoryLabel: "Agrícola · Montana",
    ref: "455.508",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Plantadeira Montana · Linha · SAE 9254",
    description: [
      "Mola de linha para plantadeiras Montana. Reposição direta do código original do fabricante.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254", "Aço Carbono"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Zinco"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.5,
    ratingCount: 11,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-jump.png",
    diameterWire: 5,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "5,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Plantadeira Montana" },
      ],
    },
  },

  // ---------- TATU ----------
  {
    slug: "mola-tatu-disco-pst",
    name: "Mola Disco Tatu PST",
    shortName: "Mola Tatu Disco",
    category: "agricola",
    categoryLabel: "Agrícola · Tatu",
    ref: "050.30.30.609",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Disco Tatu PST · Pressão · SAE 9254",
    description: [
      "Mola de pressão do disco duplo para plantadeiras Tatu Marchesan série PST. Reposição direta do original com prazo curto de entrega.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Zinco"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
      { kind: "neutro", label: "Original Tatu" },
    ],
    rating: 4.9,
    ratingCount: 63,
    bulk: [
      { qty: "1–9 un", price: "Consulte" },
      { qty: "10+ un", price: "Atacado" },
    ],
    imageTone: "dark",
    image: "/products/mola-industrial.png",
    diameterWire: 7,
    specs: {
      dimensoes: [
        { key: "Diâmetro do arame", value: "7,0 mm" },
        { key: "Aplicação", value: "Disco duplo Tatu PST" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Função", value: "Pressão do conjunto sulcador" },
      ],
    },
  },
  {
    slug: "mola-tatu-plantadeira-solo",
    name: "Mola Plantadeira Tatu Solo",
    shortName: "Mola Tatu Solo",
    category: "agricola",
    categoryLabel: "Agrícola · Tatu",
    ref: "050.30.30.378",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Plantadeira Tatu Solo · Linha · Aço Carbono",
    description: [
      "Mola da linha de plantio para Plantadeira Tatu Solo. Aço SAE 9254 com tratamento anticorrosivo.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254", "Aço Carbono"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 28,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-jump.png",
    diameterWire: 6,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "6,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Plantadeira Tatu Solo" },
      ],
    },
  },
  {
    slug: "mola-tatu-limpa-trilho",
    name: "Mola Limpa-Trilho Tatu",
    shortName: "Mola Tatu Limpa-Trilho",
    category: "agricola",
    categoryLabel: "Agrícola · Tatu",
    ref: "050.30.30.343",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Limpa-trilho Tatu · Aço Carbono",
    description: [
      "Mola do limpa-trilho/limpador frontal para plantadeiras Tatu Marchesan.",
    ],
    material: "Aço Carbono",
    materials: ["Aço Carbono", "Aço SAE 9254"],
    acabamento: "Zinco",
    acabamentos: ["Zinco", "Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.5,
    ratingCount: 17,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-customizada.png",
    diameterWire: 4,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "4,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Aplicação", value: "Limpa-trilho Tatu" },
      ],
    },
  },

  // ---------- JUMIL ----------
  {
    slug: "mola-jumil-jm-2090",
    name: "Mola Plantadeira Jumil JM2090",
    shortName: "Mola Jumil JM2090",
    category: "agricola",
    categoryLabel: "Agrícola · Jumil",
    ref: "27.05.119",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Plantadeira Jumil JM2090 · Linha · SAE 9254",
    description: [
      "Mola da linha de plantio para plantadeiras Jumil série JM2090. Reposição original com garantia técnica Incomolas.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
      { kind: "neutro", label: "Original Jumil" },
    ],
    rating: 4.8,
    ratingCount: 35,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-jump.png",
    diameterWire: 6,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "6,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Plantadeira Jumil JM2090" },
      ],
    },
  },
  {
    slug: "mola-jumil-magnum",
    name: "Mola Linha Jumil Magnum",
    shortName: "Mola Jumil Magnum",
    category: "agricola",
    categoryLabel: "Agrícola · Jumil",
    ref: "35.01.024",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Jumil Magnum · Linha de plantio · SAE 9254",
    description: [
      "Mola da linha de plantio para plantadeiras Jumil Magnum. Ideal para sistemas pneumáticos com alta exigência mecânica.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 19,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-jump.png",
    diameterWire: 7,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "7,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Plantadeira Jumil Magnum" },
      ],
    },
  },
  {
    slug: "mola-jumil-adubadeira",
    name: "Mola Adubadeira Jumil",
    shortName: "Mola Jumil Adubadeira",
    category: "agricola",
    categoryLabel: "Agrícola · Jumil",
    ref: "27.18.811",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Adubadeira Jumil · SAE 9254",
    description: [
      "Mola para conjunto adubador de plantadeiras Jumil. Reposição compatível com toda a linha JM.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254", "Aço Carbono"],
    acabamento: "Zinco",
    acabamentos: ["Zinco", "Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.6,
    ratingCount: 12,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-customizada.png",
    diameterWire: 5,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "5,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Adubadeira Jumil" },
      ],
    },
  },

  // ---------- SEMEATO ----------
  {
    slug: "mola-semeato-tdng",
    name: "Mola Semeadeira Semeato TDNG",
    shortName: "Mola Semeato TDNG",
    category: "agricola",
    categoryLabel: "Agrícola · Semeato",
    ref: "15.07.00.13",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Semeato TDNG · Linha · SAE 9254",
    description: [
      "Mola da linha de plantio para semeadeiras Semeato TDNG. Compatível com Personale Drill e variantes.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
      { kind: "neutro", label: "Original Semeato" },
    ],
    rating: 4.8,
    ratingCount: 41,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-jump.png",
    diameterWire: 6,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "6,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Semeato TDNG" },
      ],
    },
  },
  {
    slug: "mola-semeato-par",
    name: "Mola Linha Semeato PAR",
    shortName: "Mola Semeato PAR",
    category: "agricola",
    categoryLabel: "Agrícola · Semeato",
    ref: "15.07.00.21",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Semeato PAR · SAE 9254",
    description: ["Mola da linha de plantio para semeadeiras Semeato PAR."],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 18,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-jump.png",
    diameterWire: 6,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "6,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Semeato PAR" },
      ],
    },
  },
  {
    slug: "mola-semeato-disco-duplo",
    name: "Mola Disco Duplo Semeato",
    shortName: "Mola Semeato Disco",
    category: "agricola",
    categoryLabel: "Agrícola · Semeato",
    ref: "03.07.00.13",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Disco duplo Semeato · SAE 9254",
    description: [
      "Mola de pressão do conjunto disco duplo Semeato. Mantém carga uniforme sobre o sulcador.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.8,
    ratingCount: 24,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-industrial.png",
    diameterWire: 7,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "7,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Função", value: "Pressão do disco duplo" },
      ],
    },
  },

  // ---------- MASSEY FERGUSON ----------
  {
    slug: "mola-mf-patim",
    name: "Mola Patim Massey Ferguson",
    shortName: "Mola MF Patim",
    category: "agricola",
    categoryLabel: "Agrícola · Massey Ferguson",
    ref: "314.444",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Patim freio MF · Aço SAE 9254 · 4,5mm",
    description: [
      "Mola do patim de freio para tratores Massey Ferguson. Compatível com a linha MF 265, 275, 290 e variantes.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 21,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-customizada.png",
    diameterWire: 4.5,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "4,5 mm" }],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Patim de freio MF" },
      ],
    },
  },
  {
    slug: "mola-mf-embreagem",
    name: "Mola Embreagem MF 275/290",
    shortName: "Mola MF Embreagem",
    category: "agricola",
    categoryLabel: "Agrícola · Massey Ferguson",
    ref: "322.988",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Embreagem MF 275/290 · Aço Especial",
    description: [
      "Mola para conjunto de embreagem dos tratores Massey Ferguson 275 e 290. Reposição direta com tratamento térmico controlado.",
    ],
    material: "Aço Especial",
    materials: ["Aço Especial", "Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Natural"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.8,
    ratingCount: 16,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-industrial.png",
    diameterWire: 5,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "5,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço Especial" },
        { key: "Aplicação", value: "Embreagem MF 275/290" },
      ],
    },
  },

  // ---------- NEW HOLLAND ----------
  {
    slug: "mola-nh-cr",
    name: "Mola Colheitadeira New Holland CR",
    shortName: "Mola NH CR",
    category: "agricola",
    categoryLabel: "Agrícola · New Holland",
    ref: "180.001",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Colheitadeira NH série CR · SAE 9254",
    description: [
      "Mola para colheitadeiras New Holland série CR. Reposição compatível com a linha completa CR 5.85, 6.80, 7.90 e variantes.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
      { kind: "neutro", label: "Compat. CR/CX" },
    ],
    rating: 4.9,
    ratingCount: 33,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-caminhao.png",
    diameterWire: 7,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "7,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Colheitadeira NH CR" },
      ],
    },
  },
  {
    slug: "mola-nh-tc",
    name: "Mola Colheitadeira NH TC",
    shortName: "Mola NH TC",
    category: "agricola",
    categoryLabel: "Agrícola · New Holland",
    ref: "9577.762",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Colheitadeira NH série TC · SAE 9254",
    description: [
      "Mola para colheitadeiras New Holland série TC. Reposição compatível com TC 5.30, 5.70 e variantes.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 19,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-caminhao.png",
    diameterWire: 6,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "6,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Colheitadeira NH TC" },
      ],
    },
  },
  {
    slug: "mola-nh-plataforma",
    name: "Mola Plataforma New Holland",
    shortName: "Mola NH Plataforma",
    category: "agricola",
    categoryLabel: "Agrícola · New Holland",
    ref: "180.062",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Plataforma NH · Sustentação · SAE 9254",
    description: [
      "Mola de sustentação para plataformas de corte New Holland. Mantém o equilíbrio do conjunto durante a colheita.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.6,
    ratingCount: 14,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-industrial.png",
    diameterWire: 8,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "8,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Plataforma NH" },
      ],
    },
  },

  // ---------- JACTO ----------
  {
    slug: "mola-jacto-advance",
    name: "Mola Pulverizador Jacto Advance",
    shortName: "Mola Jacto Advance",
    category: "agricola",
    categoryLabel: "Agrícola · Jacto",
    ref: "A-12.111",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Pulverizador Jacto Advance · Inox AISI 304",
    description: [
      "Mola em aço inox para pulverizadores Jacto Advance. Resistente à corrosão de defensivos e fertilizantes líquidos.",
    ],
    material: "Inox AISI 304",
    materials: ["Inox AISI 304", "Aço SAE 9254"],
    acabamento: "Natural",
    acabamentos: ["Natural"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
      { kind: "neutro", label: "Anti-corrosão" },
    ],
    rating: 4.8,
    ratingCount: 27,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "steel",
    image: "/products/mola-customizada.png",
    diameterWire: 4,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "4,0 mm" }],
      desempenho: [
        { key: "Material", value: "Inox AISI 304" },
        { key: "Aplicação", value: "Pulverizador Advance" },
      ],
    },
  },
  {
    slug: "mola-jacto-cuba",
    name: "Mola Cuba Jacto",
    shortName: "Mola Jacto Cuba",
    category: "agricola",
    categoryLabel: "Agrícola · Jacto",
    ref: "A-15.789",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Cuba Jacto · Inox AISI 304",
    description: ["Mola da cuba de pulverização Jacto, em aço inox."],
    material: "Inox AISI 304",
    materials: ["Inox AISI 304"],
    acabamento: "Natural",
    acabamentos: ["Natural"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 15,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "steel",
    image: "/products/mola-customizada.png",
    diameterWire: 3,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "3,0 mm" }],
      desempenho: [
        { key: "Material", value: "Inox AISI 304" },
        { key: "Aplicação", value: "Cuba pulverizador Jacto" },
      ],
    },
  },

  // ---------- SLC ----------
  {
    slug: "mola-slc-sp9000",
    name: "Mola Plantadeira SLC SP 9000",
    shortName: "Mola SLC SP9000",
    category: "agricola",
    categoryLabel: "Agrícola · SLC",
    ref: "CQ-13.999",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Plantadeira SLC SP 9000 · SAE 9254",
    description: [
      "Mola da linha de plantio para plantadeiras SLC (John Deere) SP 9000.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
      { kind: "neutro", label: "Compat. SLC/JD" },
    ],
    rating: 4.8,
    ratingCount: 31,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-jump.png",
    diameterWire: 6,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "6,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Plantadeira SLC SP 9000" },
      ],
    },
  },
  {
    slug: "mola-slc-colheitadeira",
    name: "Mola Colheitadeira SLC",
    shortName: "Mola SLC Colheitadeira",
    category: "agricola",
    categoryLabel: "Agrícola · SLC",
    ref: "CQ-21.448",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Colheitadeira SLC · SAE 9254",
    description: [
      "Mola para colheitadeiras SLC (John Deere). Reposição compatível com toda a linha 1100/1200.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 22,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-caminhao.png",
    diameterWire: 7,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "7,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Colheitadeira SLC/JD" },
      ],
    },
  },
  {
    slug: "mola-slc-tdf",
    name: "Mola Tomada de Força SLC",
    shortName: "Mola SLC TDF",
    category: "agricola",
    categoryLabel: "Agrícola · SLC",
    ref: "CQ-30.037",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Tomada de força SLC · Aço Especial",
    description: ["Mola da tomada de força (TDF) para tratores SLC John Deere."],
    material: "Aço Especial",
    materials: ["Aço Especial", "Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.6,
    ratingCount: 11,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-industrial.png",
    diameterWire: 8,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "8,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço Especial" },
        { key: "Aplicação", value: "TDF John Deere/SLC" },
      ],
    },
  },

  // ---------- IDEAL ----------
  {
    slug: "mola-ideal-linha",
    name: "Mola Linha Ideal",
    shortName: "Mola Ideal Linha",
    category: "agricola",
    categoryLabel: "Agrícola · Ideal",
    ref: "89.000.974.5500",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Linha Ideal · SAE 9254",
    description: ["Mola de linha para implementos agrícolas Ideal."],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.5,
    ratingCount: 9,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-jump.png",
    diameterWire: 5,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "5,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Linha Ideal" },
      ],
    },
  },
  {
    slug: "mola-ideal-plantadeira",
    name: "Mola Plantadeira Ideal",
    shortName: "Mola Ideal Plant.",
    category: "agricola",
    categoryLabel: "Agrícola · Ideal",
    ref: "87.000.971.4915",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Plantadeira Ideal · SAE 9254",
    description: ["Mola para plantadeiras Ideal — pressão da linha."],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.6,
    ratingCount: 12,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-jump.png",
    diameterWire: 6,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "6,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Plantadeira Ideal" },
      ],
    },
  },

  // ---------- NOGUEIRA ----------
  {
    slug: "mola-nogueira-triturador",
    name: "Mola Triturador Nogueira DPM",
    shortName: "Mola Nogueira DPM",
    category: "agricola",
    categoryLabel: "Agrícola · Nogueira",
    ref: "50.10.234",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Triturador Nogueira DPM · Aço Especial",
    description: [
      "Mola para trituradores forrageiros Nogueira DPM. Reposição direta com tratamento térmico controlado.",
    ],
    material: "Aço Especial",
    materials: ["Aço Especial", "Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 18,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-industrial.png",
    diameterWire: 8,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "8,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço Especial" },
        { key: "Aplicação", value: "Triturador Nogueira DPM" },
      ],
    },
  },

  // ---------- MENEGAS ----------
  {
    slug: "mola-menegas-linha",
    name: "Mola Linha Menegas",
    shortName: "Mola Menegas",
    category: "agricola",
    categoryLabel: "Agrícola · Menegas",
    ref: "50.50.149",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Linha Menegas · Aço Carbono",
    description: ["Mola para implementos agrícolas Menegas."],
    material: "Aço Carbono",
    materials: ["Aço Carbono", "Aço SAE 9254"],
    acabamento: "Zinco",
    acabamentos: ["Zinco", "Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.5,
    ratingCount: 8,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-customizada.png",
    diameterWire: 5,
    specs: {
      dimensoes: [{ key: "Diâmetro do arame", value: "5,0 mm" }],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Aplicação", value: "Implementos Menegas" },
      ],
    },
  },

  // ---------- AGRÍCOLA SOB MEDIDA ----------
  {
    slug: "mola-agricola-sob-medida",
    name: "Mola Agrícola Sob Medida",
    shortName: "Mola Agrícola Custom",
    category: "agricola",
    categoryLabel: "Agrícola · Projeto especial",
    ref: "INC-AGR-000",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "projeto especial",
    spec: "Reposição de mola por código original · Qualquer fabricante",
    description: [
      "Não encontrou o código no catálogo? Envie a referência original do fabricante (Baldan, Tatu, Jumil, Semeato, Massey Ferguson, New Holland, Jacto, SLC, Ideal, Nogueira, Menegas ou outros) e produzimos sob medida em até 7 dias úteis.",
      "Atendemos pequenos produtores, oficinas agrícolas, revendedores e grandes propriedades.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254", "Aço Carbono", "Inox AISI 304", "Aço Especial"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Zinco", "Cromo", "Natural"],
    disponibilidade: ["sobmedida", "atacado"],
    badges: [
      { kind: "sobmedida", label: "Sob Medida" },
      { kind: "neutro", label: "Qualquer fabricante" },
    ],
    rating: 5,
    ratingCount: 31,
    bulk: [{ qty: "Sob projeto", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-customizada.png",
    diameterWire: 0,
    specs: {
      dimensoes: [{ key: "Configuração", value: "Conforme original" }],
      desempenho: [
        { key: "Prazo de produção", value: "Até 7 dias úteis" },
        { key: "Documento necessário", value: "Código original ou amostra" },
      ],
    },
  },

  // ============================================================
  // LINHA AUTOMOTIVA — ampliação com molas da linha pesada (GMA)
  // Scania, Volvo, Mercedes-Benz, Randon, Guerra, Noma
  // ============================================================
  {
    slug: "mola-carreta-randon-antiga",
    name: "Mola Carreta Randon Antiga Reta",
    shortName: "Mola Carreta Randon",
    category: "automotivo",
    categoryLabel: "Automotivo · Carreta",
    ref: "I-1001",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Carreta Randon Antiga · ø arame 4mm · L 210mm",
    description: [
      "Mola reta para carreta Randon antiga. Aço SAE 9254 de 4mm com comprimento de 210mm. Reposição direta para frotistas e revendedores.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 14,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-caminhao.png",
    diameterWire: 4,
    specs: {
      dimensoes: [
        { key: "Diâmetro do arame", value: "4,0 mm" },
        { key: "Comprimento", value: "210 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Carreta Randon antiga" },
      ],
    },
  },
  {
    slug: "mola-carreta-randon-moderna",
    name: "Mola Carreta Randon Moderna Q-Plus",
    shortName: "Mola Randon Q-Plus",
    category: "automotivo",
    categoryLabel: "Automotivo · Carreta",
    ref: "I-1005",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Randon Moderna Q-Plus · ø arame 4,8mm · L 210mm",
    description: [
      "Mola para carretas Randon modernas linha Q-Plus. Reposição direta com tratamento térmico controlado.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.8,
    ratingCount: 19,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-caminhao.png",
    diameterWire: 4.8,
    specs: {
      dimensoes: [
        { key: "Diâmetro do arame", value: "4,8 mm" },
        { key: "Comprimento", value: "210 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Carreta Randon Q-Plus" },
      ],
    },
  },
  {
    slug: "mola-patim-scania",
    name: "Mola Patim Traseira Scania",
    shortName: "Mola Patim Scania",
    category: "automotivo",
    categoryLabel: "Automotivo · Scania",
    ref: "I-1011",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Patim Scania · ø arame 5mm · L 210mm",
    description: [
      "Mola do patim de freio traseiro para Scania. Aplicação para linha 111/112/113 e variantes.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.8,
    ratingCount: 22,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-customizada.png",
    diameterWire: 5,
    specs: {
      dimensoes: [
        { key: "Diâmetro do arame", value: "5,0 mm" },
        { key: "Comprimento", value: "210 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Patim traseiro Scania" },
      ],
    },
  },
  {
    slug: "mola-capu-scania",
    name: "Mola Capô Scania",
    shortName: "Mola Capô Scania",
    category: "automotivo",
    categoryLabel: "Automotivo · Scania",
    ref: "I-1010",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Capô Scania · ø arame 6,5mm · L 240mm",
    description: ["Mola do capô para caminhões Scania."],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.6,
    ratingCount: 10,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-jump.png",
    diameterWire: 6.5,
    specs: {
      dimensoes: [
        { key: "Diâmetro do arame", value: "6,5 mm" },
        { key: "Comprimento", value: "240 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Capô Scania" },
      ],
    },
  },
  {
    slug: "mola-patim-volvo",
    name: "Mola Patim Dianteira Volvo",
    shortName: "Mola Patim Volvo",
    category: "automotivo",
    categoryLabel: "Automotivo · Volvo",
    ref: "I-1015",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Patim Volvo · ø arame 5,5mm · L 215mm",
    description: [
      "Mola do patim de freio dianteiro para caminhões Volvo. Compatível com NL10, NL12 e variantes.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 17,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-customizada.png",
    diameterWire: 5.5,
    specs: {
      dimensoes: [
        { key: "Diâmetro do arame", value: "5,5 mm" },
        { key: "Comprimento", value: "215 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Patim dianteiro Volvo NL10/NL12" },
      ],
    },
  },
  {
    slug: "mola-patim-mb-1313",
    name: "Mola Patim MB 1313",
    shortName: "Mola Patim MB",
    category: "automotivo",
    categoryLabel: "Automotivo · Mercedes-Benz",
    ref: "I-1025",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "MB 1313 · ø arame 5mm · L 250mm",
    description: [
      "Mola do patim de freio dianteiro para Mercedes-Benz 1313. Reposição direta com tratamento anticorrosivo.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.8,
    ratingCount: 24,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-customizada.png",
    diameterWire: 5,
    specs: {
      dimensoes: [
        { key: "Diâmetro do arame", value: "5,0 mm" },
        { key: "Comprimento", value: "250 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Patim dianteiro MB 1313" },
      ],
    },
  },
  {
    slug: "mola-cambao-randon",
    name: "Mola Cambão Randon (Canavieira)",
    shortName: "Mola Cambão Randon",
    category: "automotivo",
    categoryLabel: "Automotivo · Canavieira",
    ref: "I-1033",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Cambão Randon · ø arame 8mm · L 380mm",
    description: [
      "Mola do cambão para a linha canavieira Randon. Aço SAE 9254 de 8mm para alta solicitação mecânica.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254", "Aço Especial"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.8,
    ratingCount: 13,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-caminhao.png",
    diameterWire: 8,
    specs: {
      dimensoes: [
        { key: "Diâmetro do arame", value: "8,0 mm" },
        { key: "Comprimento", value: "380 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Cambão canavieira Randon" },
      ],
    },
  },
  {
    slug: "mola-para-choque-noma",
    name: "Mola Para-Choque Noma",
    shortName: "Mola Para-Choque",
    category: "automotivo",
    categoryLabel: "Automotivo · Para-Choque",
    ref: "I-1037",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Para-choque Noma · ø arame 4mm · L 190mm/320mm",
    description: [
      "Mola para para-choque de caminhões Noma. Disponível nas medidas 19cm e 32cm conforme a aplicação.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254", "Aço Carbono"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Zinco"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.6,
    ratingCount: 9,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-caminhao.png",
    diameterWire: 4,
    specs: {
      dimensoes: [
        { key: "Diâmetro do arame", value: "4,0 mm" },
        { key: "Comprimentos disponíveis", value: "190 mm · 320 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Aplicação", value: "Para-choque caminhão Noma" },
      ],
    },
  },

  // ============================================================
  // LINHA CARROCERIA — Peças GMA (engates, dobradiças, presilhas)
  // Catálogo de Peças Automotivas e Carrocerias
  // ============================================================
  {
    slug: "dobradica-tampa-randon-antiga",
    name: "Dobradiça da Tampa Randon Antiga",
    shortName: "Dobradiça Randon Antiga",
    category: "carroceria",
    categoryLabel: "Carroceria · Dobradiça",
    ref: "GMA-001",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Dobradiça tampa Randon antiga · 209 mm",
    description: [
      "Dobradiça da tampa para carrocerias Randon modelo antigo. Comprimento total de 209 mm.",
      "Peça forjada em aço carbono com tratamento de superfície. Atendemos frotistas, oficinas e revendedores.",
    ],
    material: "Aço Carbono",
    materials: ["Aço Carbono"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Zinco"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 26,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/carroceria-dobradica-randon-antiga.png",
    diameterWire: 0,
    specs: {
      dimensoes: [{ key: "Comprimento", value: "209 mm" }],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Aplicação", value: "Tampa carroceria Randon antiga" },
      ],
    },
  },
  {
    slug: "dobradica-tampa-randon-moderna",
    name: "Dobradiça da Tampa Randon Moderna",
    shortName: "Dobradiça Randon Moderna",
    category: "carroceria",
    categoryLabel: "Carroceria · Dobradiça",
    ref: "GMA-002",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Dobradiça tampa Randon moderna · 178 mm",
    description: [
      "Dobradiça da tampa para carrocerias Randon modelo moderno. Comprimento total de 178 mm.",
    ],
    material: "Aço Carbono",
    materials: ["Aço Carbono"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Zinco"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.8,
    ratingCount: 31,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/carroceria-dobradica-randon-moderna.png",
    diameterWire: 0,
    specs: {
      dimensoes: [{ key: "Comprimento", value: "178 mm" }],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Aplicação", value: "Tampa carroceria Randon moderna" },
      ],
    },
  },
  {
    slug: "engate-j-grade-carreta",
    name: "Engate 'J' Grade da Carreta",
    shortName: "Engate J Carreta",
    category: "carroceria",
    categoryLabel: "Carroceria · Engate",
    ref: "GMA-005",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Engate 'J' grade · 85 mm",
    description: ["Engate 'J' para grade da carreta. Comprimento 85 mm."],
    material: "Aço Carbono",
    materials: ["Aço Carbono"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Zinco"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.6,
    ratingCount: 15,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/carroceria-engate-j.png",
    diameterWire: 0,
    specs: {
      dimensoes: [{ key: "Comprimento", value: "85 mm" }],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Aplicação", value: "Grade da carreta" },
      ],
    },
  },
  {
    slug: "engate-rapido-dobradica",
    name: "Engate Rápido Dobradiça",
    shortName: "Engate Rápido",
    category: "carroceria",
    categoryLabel: "Carroceria · Engate",
    ref: "GMA-006",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Engate rápido · L 32 × C 70 mm",
    description: [
      "Engate rápido para dobradiças de carroceria. Largura 32 mm, comprimento 70 mm.",
    ],
    material: "Aço Carbono",
    materials: ["Aço Carbono"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 22,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/carroceria-engate-rapido.png",
    diameterWire: 0,
    specs: {
      dimensoes: [
        { key: "Largura", value: "32 mm" },
        { key: "Comprimento", value: "70 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Aplicação", value: "Engate rápido dobradiça" },
      ],
    },
  },
  {
    slug: "rolete-tombador",
    name: "Conjunto Rolete Tombador",
    shortName: "Rolete Tombador",
    category: "carroceria",
    categoryLabel: "Carroceria · Tombador",
    ref: "GMA-007",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "conjunto",
    spec: "Rolete tombador · Tampa traseira",
    description: [
      "Conjunto rolete tombador para tampa traseira de carrocerias.",
    ],
    material: "Aço Carbono",
    materials: ["Aço Carbono"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 11,
    bulk: [{ qty: "1+ conj.", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/carroceria-rolete-tombador.png",
    diameterWire: 0,
    specs: {
      dimensoes: [{ key: "Tipo", value: "Conjunto completo" }],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Aplicação", value: "Tampa traseira" },
      ],
    },
  },
  {
    slug: "dobradica-tombador-superior",
    name: "Dobradiça Tombador Superior",
    shortName: "Dobradiça Tombador Sup.",
    category: "carroceria",
    categoryLabel: "Carroceria · Tombador",
    ref: "GMA-010",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Dobradiça tombador superior · 155 mm",
    description: [
      "Dobradiça do tombador superior para carrocerias. Comprimento 155 mm.",
    ],
    material: "Aço Carbono",
    materials: ["Aço Carbono"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.6,
    ratingCount: 9,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/carroceria-dobradica-tombador.png",
    diameterWire: 0,
    specs: {
      dimensoes: [{ key: "Comprimento", value: "155 mm" }],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Aplicação", value: "Tombador superior" },
      ],
    },
  },
  {
    slug: "engate-femea-carroceria",
    name: "Engate Fêmea da Carroceria",
    shortName: "Engate Fêmea",
    category: "carroceria",
    categoryLabel: "Carroceria · Engate",
    ref: "GMA-016",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Engate fêmea carroceria · 135 mm",
    description: [
      "Engate fêmea grande para carroceria. Comprimento 135 mm.",
    ],
    material: "Aço Carbono",
    materials: ["Aço Carbono"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 14,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/carroceria-engate-femea.png",
    diameterWire: 0,
    specs: {
      dimensoes: [{ key: "Comprimento", value: "135 mm" }],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Aplicação", value: "Carroceria" },
      ],
    },
  },
  {
    slug: "aranha-assoalho",
    name: "Aranha do Assoalho",
    shortName: "Aranha Assoalho",
    category: "carroceria",
    categoryLabel: "Carroceria · Fixação",
    ref: "GMA-019",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Aranha do assoalho · Aço Carbono",
    description: ["Aranha para fixação do assoalho de carrocerias."],
    material: "Aço Carbono",
    materials: ["Aço Carbono"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Zinco"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.5,
    ratingCount: 7,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/carroceria-aranha-assoalho.png",
    diameterWire: 0,
    specs: {
      dimensoes: [{ key: "Tipo", value: "Fixação" }],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Aplicação", value: "Assoalho carroceria" },
      ],
    },
  },
  {
    slug: "trava-aranha-randon",
    name: "Trava Aranha Randon/Master",
    shortName: "Trava Aranha Randon",
    category: "carroceria",
    categoryLabel: "Carroceria · Trava",
    ref: "GMA-076",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Trava aranha Randon/Master · 139 × 80,3 mm",
    description: [
      "Trava aranha para Randon e Master. Dimensões 139 × 80,3 mm.",
    ],
    material: "Aço Carbono",
    materials: ["Aço Carbono"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.6,
    ratingCount: 11,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/carroceria-trava-aranha.png",
    diameterWire: 0,
    specs: {
      dimensoes: [{ key: "Dimensões", value: "139 × 80,3 mm" }],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Aplicação", value: "Aranha Randon/Master" },
      ],
    },
  },
  {
    slug: "pino-quebra-dedo",
    name: "Pino Quebra-Dedo c/ Corrente",
    shortName: "Pino Quebra-Dedo",
    category: "carroceria",
    categoryLabel: "Carroceria · Pino",
    ref: "GMA-061/A",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Pino quebra-dedo c/ corrente · 1/4 × 2'' / 5/16 × 2''",
    description: [
      "Pino quebra-dedo com corrente de segurança. Disponível nas bitolas 1/4 × 2'' e 5/16 × 2''.",
    ],
    material: "Aço Carbono",
    materials: ["Aço Carbono"],
    acabamento: "Zinco",
    acabamentos: ["Zinco", "Natural"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.8,
    ratingCount: 28,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/carroceria-pino-quebra-dedo.png",
    diameterWire: 0,
    specs: {
      dimensoes: [{ key: "Bitolas", value: "1/4 × 2'' · 5/16 × 2''" }],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Aplicação", value: "Carrocerias com corrente de segurança" },
      ],
    },
  },
  {
    slug: "presilha-u-26mm",
    name: "Presilha 'U' 26 mm",
    shortName: "Presilha U",
    category: "carroceria",
    categoryLabel: "Carroceria · Presilha",
    ref: "GMA-066",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Presilha 'U' s/ porca · 26 mm",
    description: ["Presilha em 'U' sem porca, bitola 26 mm."],
    material: "Aço Carbono",
    materials: ["Aço Carbono"],
    acabamento: "Zinco",
    acabamentos: ["Zinco", "Natural"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.6,
    ratingCount: 12,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/carroceria-presilha-u.png",
    diameterWire: 0,
    specs: {
      dimensoes: [{ key: "Bitola", value: "26 mm" }],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Aplicação", value: "Fixação de cintas e estruturas" },
      ],
    },
  },
  {
    slug: "arco-lona-guerra",
    name: "Arco de Lona Guerra",
    shortName: "Arco de Lona",
    category: "carroceria",
    categoryLabel: "Carroceria · Arco",
    ref: "GMA-073",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Arco lona Guerra · 2.450 mm",
    description: [
      "Arco de lona para carrocerias Guerra. Comprimento 2.450 mm. Outras medidas (2.380 mm graneleira, 2.500 mm bi-trem, 2.580 mm Noma) sob consulta.",
    ],
    material: "Aço Carbono",
    materials: ["Aço Carbono"],
    acabamento: "Zinco",
    acabamentos: ["Zinco", "Fosfato Preto"],
    disponibilidade: ["estoque", "atacado", "sobmedida"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 18,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/carroceria-arco-lona.png",
    diameterWire: 0,
    specs: {
      dimensoes: [
        { key: "Comprimento padrão", value: "2.450 mm" },
        { key: "Outras medidas", value: "2.380 · 2.500 · 2.520 · 2.580 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Aplicação", value: "Carroceria Guerra/Noma/Graneleira" },
      ],
    },
  },
  {
    slug: "arruela-trava-randon",
    name: "Arruela c/ Trava Randon",
    shortName: "Arruela Trava",
    category: "carroceria",
    categoryLabel: "Carroceria · Arruela",
    ref: "GMA-082",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "unidade",
    spec: "Arruela trava Randon · 120 × 80 mm",
    description: [
      "Arruela com trava para conjunto eixo de carretas Randon. Medidas 120 × 80 mm.",
    ],
    material: "Aço Carbono",
    materials: ["Aço Carbono"],
    acabamento: "Zinco",
    acabamentos: ["Zinco"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.5,
    ratingCount: 8,
    bulk: [{ qty: "1+ un", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/carroceria-arruela-trava.png",
    diameterWire: 0,
    specs: {
      dimensoes: [{ key: "Dimensões", value: "120 × 80 mm" }],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Aplicação", value: "Eixo carreta Randon" },
      ],
    },
  },
  {
    slug: "corrente-engate-carroceria",
    name: "Corrente para Engate da Carroceria",
    shortName: "Corrente Engate",
    category: "carroceria",
    categoryLabel: "Carroceria · Corrente",
    ref: "GMA-060",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "metro",
    spec: "Corrente engate carroceria · 1,33 m",
    description: [
      "Corrente para engate de carrocerias. Comprimento 1,33 m. Disponível também versão fueiro (corrente do pino do fueiro).",
    ],
    material: "Aço Carbono",
    materials: ["Aço Carbono"],
    acabamento: "Zinco",
    acabamentos: ["Zinco", "Natural"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.6,
    ratingCount: 10,
    bulk: [{ qty: "1+ m", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/carroceria-corrente.png",
    diameterWire: 0,
    specs: {
      dimensoes: [{ key: "Comprimento", value: "1,33 m" }],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Aplicação", value: "Engate da carroceria" },
      ],
    },
  },
];

export const PRODUCTS: Product[] = [...BASE_PRODUCTS, ...PDF_CATALOG_PRODUCTS];

export function getProduct(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getRelated(slug: string, n = 4): Product[] {
  const cur = getProduct(slug);
  if (!cur) return PRODUCTS.slice(0, n);
  return [
    ...PRODUCTS.filter((p) => p.category === cur.category && p.slug !== slug),
    ...PRODUCTS.filter((p) => p.category !== cur.category && p.slug !== slug),
  ].slice(0, n);
}
