import type { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    slug: "mola-barra-olimpica",
    name: "Mola para Barra Olímpica",
    shortName: "Mola Barra Olímpica",
    category: "academia",
    categoryLabel: "Molas para Academia",
    ref: "INC-ACM-001",
    price: 34.9,
    unitLabel: "por par · à vista no pix",
    spec: "ø 45mm · ø arame 4,5mm · L 115mm · SAE 9254",
    description: [
      "A Mola para Barra Olímpica Incomolas é fabricada em aço SAE 9254 de alta resistência, com tratamento de fosfato preto para proteção contra oxidação e melhor retenção de lubrificantes. Desenvolvida para barras de 45mm de diâmetro, padrão olímpico.",
      "Cada par passa por inspeção dimensional e de carga antes do envio. A constante de mola de 8,4 kgf/mm garante acionamento seguro e suave, com longa vida útil mesmo em uso intenso em academias.",
      "Disponível em acabamentos zinco, cromo e natural para aplicações específicas. Para pedidos de grande volume ou especificações fora do padrão, entre em contato com nossa equipe técnica.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254", "Aço Carbono", "Inox AISI 304"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Zinco", "Cromo", "Natural"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado disponível" },
      { kind: "par", label: "Vendido em Par" },
    ],
    rating: 4.0,
    ratingCount: 38,
    bulk: [
      { qty: "1–9 pares", price: "R$ 34,90" },
      { qty: "10–49 pares", price: "R$ 29,90", save: "–14%" },
      { qty: "50–199 pares", price: "R$ 24,90", save: "–29%" },
      { qty: "200+ pares", price: "Consulte" },
    ],
    imageTone: "steel",
    image: "/products/mola-academia.png",
    diameterWire: 4.5,
    specs: {
      dimensoes: [
        { key: "Diâmetro externo", value: "45 mm" },
        { key: "Diâmetro do arame", value: "4,5 mm" },
        { key: "Comprimento livre", value: "115 mm" },
        { key: "Comprimento sólido", value: "54 mm" },
        { key: "Número de espiras ativas", value: "11" },
        { key: "Número de espiras totais", value: "13" },
        { key: "Passo", value: "5,5 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Acabamento padrão", value: "Fosfato preto" },
        { key: "Constante de mola (k)", value: "8,4 kgf/mm" },
        { key: "Carga de trabalho máx.", value: "120 kgf" },
        { key: "Deflexão máx. (trabalho)", value: "61 mm" },
        { key: "Sentido de enrolamento", value: "Dextrorso" },
        { key: "Extremidades", value: "Fechadas e retificadas" },
      ],
    },
  },
  {
    slug: "mola-barra-curta",
    name: "Mola Barra Curta",
    category: "academia",
    categoryLabel: "Molas para Academia",
    ref: "INC-ACM-002",
    price: 28.5,
    unitLabel: "por par",
    spec: "ø 38mm · ø arame 4mm · L 95mm · SAE 9254",
    description: [
      "Mola compacta para barras curtas de musculação. Aço SAE 9254 com tratamento anticorrosivo.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254", "Aço Carbono"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Zinco"],
    disponibilidade: ["estoque"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "par", label: "Par" },
    ],
    rating: 4.5,
    ratingCount: 22,
    bulk: [
      { qty: "1–9 pares", price: "R$ 28,50" },
      { qty: "10+ pares", price: "R$ 24,90", save: "–13%" },
    ],
    imageTone: "steel",
    image: "/products/mola-academia.png",
    diameterWire: 4,
    specs: {
      dimensoes: [
        { key: "Diâmetro externo", value: "38 mm" },
        { key: "Diâmetro do arame", value: "4,0 mm" },
        { key: "Comprimento livre", value: "95 mm" },
        { key: "Espiras totais", value: "11" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Carga máx.", value: "85 kgf" },
        { key: "Constante k", value: "6,2 kgf/mm" },
      ],
    },
  },
  {
    slug: "mola-leg-press",
    name: "Mola Leg Press",
    category: "academia",
    categoryLabel: "Molas para Academia",
    ref: "INC-ACM-007",
    price: 68.0,
    unitLabel: "unidade",
    spec: "ø 60mm · ø arame 6mm · L 200mm · Cromo",
    description: [
      "Mola robusta para equipamentos Leg Press. Acabamento cromado, alta durabilidade.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254", "Aço Especial"],
    acabamento: "Cromo",
    acabamentos: ["Cromo", "Zinco"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 5,
    ratingCount: 12,
    bulk: [
      { qty: "1–4 un", price: "R$ 68,00" },
      { qty: "5–19 un", price: "R$ 59,00", save: "–13%" },
      { qty: "20+ un", price: "Consulte" },
    ],
    imageTone: "chrome",
    image: "/products/mola-academia.png",
    diameterWire: 6,
    specs: {
      dimensoes: [
        { key: "Diâmetro externo", value: "60 mm" },
        { key: "Diâmetro do arame", value: "6,0 mm" },
        { key: "Comprimento livre", value: "200 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Acabamento", value: "Cromo industrial" },
        { key: "Carga máx.", value: "240 kgf" },
      ],
    },
  },
  {
    slug: "mola-haltere-20kg",
    name: "Mola Haltere 20kg",
    category: "academia",
    categoryLabel: "Molas para Academia",
    ref: "INC-ACM-014",
    price: 42.0,
    unitLabel: "por par",
    spec: "ø 50mm · ø arame 5mm · L 80mm · Cromo",
    description: ["Mola de retenção para halteres profissionais até 20kg."],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254"],
    acabamento: "Cromo",
    acabamentos: ["Cromo"],
    disponibilidade: ["estoque"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "par", label: "Par" },
    ],
    rating: 4.2,
    ratingCount: 19,
    bulk: [{ qty: "1+ pares", price: "R$ 42,00" }],
    imageTone: "chrome",
    image: "/products/mola-academia.png",
    diameterWire: 5,
    specs: {
      dimensoes: [
        { key: "Diâmetro externo", value: "50 mm" },
        { key: "Diâmetro do arame", value: "5,0 mm" },
        { key: "Comprimento livre", value: "80 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Carga máx.", value: "20 kg" },
      ],
    },
  },
  {
    slug: "kit-molas-cama-4-5m",
    name: "Kit Molas Cama 4,5m",
    shortName: "Kit Molas 4,5m",
    category: "cama",
    categoryLabel: "Cama Elástica",
    ref: "INC-CAM-072",
    price: 189.0,
    unitLabel: "kit 72 unidades",
    spec: "ø 5mm · L 180mm · Zinco · Kit 72 unidades",
    description: [
      "Kit completo com 72 molas zincadas para cama elástica de 4,5m de diâmetro. Tratamento anticorrosivo para uso externo.",
    ],
    material: "Aço Carbono",
    materials: ["Aço Carbono", "Aço SAE 9254"],
    acabamento: "Zinco",
    acabamentos: ["Zinco", "Cromo"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "kit", label: "Kit 72un" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 54,
    bulk: [
      { qty: "1 kit", price: "R$ 189,00" },
      { qty: "5+ kits", price: "R$ 165,00", save: "–13%" },
      { qty: "20+ kits", price: "Consulte" },
    ],
    imageTone: "zinc",
    image: "/products/mola-cama-elastica.png",
    diameterWire: 5,
    specs: {
      dimensoes: [
        { key: "Diâmetro do arame", value: "5,0 mm" },
        { key: "Comprimento livre", value: "180 mm" },
        { key: "Quantidade no kit", value: "72 unidades" },
      ],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Acabamento", value: "Zincado" },
        { key: "Diâmetro da cama", value: "4,5 m" },
      ],
    },
  },
  {
    slug: "kit-molas-cama-4m",
    name: "Kit Molas Cama 4m",
    shortName: "Kit Molas 4m",
    category: "cama",
    categoryLabel: "Cama Elástica",
    ref: "INC-CAM-060",
    price: 149.0,
    unitLabel: "kit 60 unidades",
    spec: "ø 5mm · L 160mm · Zinco · Kit 60 unidades",
    description: ["Kit com 60 molas zincadas para camas elásticas de 4m."],
    material: "Aço Carbono",
    materials: ["Aço Carbono"],
    acabamento: "Zinco",
    acabamentos: ["Zinco"],
    disponibilidade: ["estoque", "atacado"],
    badges: [
      { kind: "kit", label: "Kit 60un" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.6,
    ratingCount: 38,
    bulk: [
      { qty: "1 kit", price: "R$ 149,00" },
      { qty: "5+ kits", price: "R$ 132,00", save: "–11%" },
    ],
    imageTone: "zinc",
    image: "/products/mola-cama-elastica.png",
    diameterWire: 5,
    specs: {
      dimensoes: [
        { key: "Diâmetro do arame", value: "5,0 mm" },
        { key: "Comprimento livre", value: "160 mm" },
        { key: "Quantidade no kit", value: "60 unidades" },
      ],
      desempenho: [
        { key: "Material", value: "Aço Carbono" },
        { key: "Acabamento", value: "Zincado" },
        { key: "Diâmetro da cama", value: "4,0 m" },
      ],
    },
  },
  {
    slug: "mola-jump-profissional",
    name: "Mola Jump Profissional",
    shortName: "Mola Jump Pro",
    category: "jump",
    categoryLabel: "Jump / Mini Cama",
    ref: "INC-JMP-004",
    price: 8.9,
    unitLabel: "unidade",
    spec: "ø arame 4mm · L 140mm · Inox AISI 304",
    description: [
      "Mola em aço inox para jumps profissionais. Resistente à corrosão para uso em academias.",
    ],
    material: "Inox AISI 304",
    materials: ["Inox AISI 304", "Aço SAE 9254"],
    acabamento: "Natural",
    acabamentos: ["Natural"],
    disponibilidade: ["sobmedida", "atacado"],
    badges: [
      { kind: "sobmedida", label: "Sob Medida" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.8,
    ratingCount: 91,
    bulk: [
      { qty: "1–35 un", price: "R$ 8,90" },
      { qty: "36–143 un", price: "R$ 7,50", save: "–16%" },
      { qty: "144+ un", price: "Consulte" },
    ],
    imageTone: "green",
    image: "/products/mola-jump.png",
    diameterWire: 4,
    specs: {
      dimensoes: [
        { key: "Diâmetro do arame", value: "4,0 mm" },
        { key: "Comprimento livre", value: "140 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Inox AISI 304" },
        { key: "Aplicação", value: "Jump profissional" },
      ],
    },
  },
  {
    slug: "mola-compressao-industrial",
    name: "Mola Compressão Industrial",
    shortName: "Mola Compressão",
    category: "industrial",
    categoryLabel: "Industrial",
    ref: "INC-IND-022",
    price: 18.5,
    unitLabel: "unidade",
    spec: "ø 80mm · ø arame 12mm · L 300mm · Especial",
    description: [
      "Mola pesada para aplicações industriais de compressão. Sob consulta para especificações personalizadas.",
    ],
    material: "Aço Especial",
    materials: ["Aço Especial", "Aço SAE 9254"],
    acabamento: "Natural",
    acabamentos: ["Natural", "Fosfato Preto"],
    disponibilidade: ["sobmedida"],
    badges: [
      { kind: "consulte", label: "Consulte" },
      { kind: "sobmedida", label: "Sob Medida" },
    ],
    rating: 4.9,
    ratingCount: 8,
    bulk: [{ qty: "Lote mínimo", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-industrial.png",
    diameterWire: 12,
    specs: {
      dimensoes: [
        { key: "Diâmetro externo", value: "80 mm" },
        { key: "Diâmetro do arame", value: "12,0 mm" },
        { key: "Comprimento livre", value: "300 mm" },
      ],
      desempenho: [
        { key: "Material", value: "Aço Especial" },
        { key: "Aplicação", value: "Compressão industrial" },
      ],
    },
  },
  {
    slug: "mola-suspensao-carro",
    name: "Mola Suspensão — Veículo Leve",
    shortName: "Mola Suspensão Carro",
    category: "automotivo",
    categoryLabel: "Automotivo",
    ref: "INC-AUT-101",
    price: 145.0,
    unitLabel: "unidade",
    spec: "ø 110mm · ø arame 12mm · L 350mm · SAE 9254",
    description: [
      "Mola helicoidal de suspensão para veículos de passeio. Fabricada em aço SAE 9254 com tratamento térmico controlado para garantir resposta consistente em qualquer terreno.",
      "Disponível para aplicações originais ou rebaixadas. Para projetos especiais (kits sport, off-road, lift), envie a especificação completa para nossa engenharia.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254", "Aço Especial"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Zinco"],
    disponibilidade: ["estoque", "atacado", "sobmedida"],
    badges: [
      { kind: "estoque", label: "Em Estoque" },
      { kind: "atacado", label: "Atacado" },
    ],
    rating: 4.7,
    ratingCount: 26,
    bulk: [
      { qty: "1–3 un", price: "R$ 145,00" },
      { qty: "4–11 un", price: "R$ 129,00", save: "–11%" },
      { qty: "12+ un", price: "Consulte" },
    ],
    imageTone: "dark",
    image: "/products/mola-carros.png",
    diameterWire: 12,
    specs: {
      dimensoes: [
        { key: "Diâmetro externo", value: "110 mm" },
        { key: "Diâmetro do arame", value: "12,0 mm" },
        { key: "Comprimento livre", value: "350 mm" },
        { key: "Espiras totais", value: "8" },
      ],
      desempenho: [
        { key: "Material", value: "Aço SAE 9254" },
        { key: "Carga máx.", value: "780 kgf" },
        { key: "Constante k", value: "23,4 kgf/mm" },
      ],
    },
  },
  {
    slug: "mola-suspensao-caminhao",
    name: "Mola Suspensão — Caminhão",
    shortName: "Mola Caminhão",
    category: "automotivo",
    categoryLabel: "Automotivo",
    ref: "INC-AUT-220",
    price: 320.0,
    unitLabel: "unidade",
    spec: "ø 160mm · ø arame 22mm · L 480mm · Aço Especial",
    description: [
      "Mola helicoidal de alta capacidade para caminhões e veículos pesados. Resistência reforçada para cargas elevadas e uso contínuo.",
      "Atendemos frotistas, oficinas e fabricantes com lotes a partir de 10 unidades. Especificações sob medida para projetos OEM.",
    ],
    material: "Aço Especial",
    materials: ["Aço Especial", "Aço SAE 9254"],
    acabamento: "Fosfato Preto",
    acabamentos: ["Fosfato Preto", "Natural"],
    disponibilidade: ["atacado", "sobmedida"],
    badges: [
      { kind: "atacado", label: "Atacado" },
      { kind: "sobmedida", label: "Sob Medida" },
    ],
    rating: 4.9,
    ratingCount: 14,
    bulk: [
      { qty: "1–9 un", price: "R$ 320,00" },
      { qty: "10–49 un", price: "R$ 285,00", save: "–11%" },
      { qty: "50+ un", price: "Consulte" },
    ],
    imageTone: "dark",
    image: "/products/mola-caminhao.png",
    diameterWire: 22,
    specs: {
      dimensoes: [
        { key: "Diâmetro externo", value: "160 mm" },
        { key: "Diâmetro do arame", value: "22,0 mm" },
        { key: "Comprimento livre", value: "480 mm" },
        { key: "Espiras totais", value: "7" },
      ],
      desempenho: [
        { key: "Material", value: "Aço Especial" },
        { key: "Carga máx.", value: "2.100 kgf" },
        { key: "Constante k", value: "62,0 kgf/mm" },
        { key: "Aplicação", value: "Suspensão veículo pesado" },
      ],
    },
  },
  {
    slug: "mola-sob-medida",
    name: "Mola Sob Medida",
    category: "industrial",
    categoryLabel: "Industrial",
    ref: "INC-CUST-000",
    price: 0,
    priceLabel: "Consulte",
    unitLabel: "projeto especial",
    spec: "Qualquer diâmetro · Qualquer comprimento · Qualquer material",
    description: [
      "Projeto sob medida para sua aplicação. Envie suas especificações e receba um orçamento técnico em até 24h.",
    ],
    material: "Aço SAE 9254",
    materials: ["Aço SAE 9254", "Aço Carbono", "Inox AISI 304", "Aço Especial"],
    acabamento: "Natural",
    acabamentos: ["Natural", "Fosfato Preto", "Zinco", "Cromo"],
    disponibilidade: ["sobmedida"],
    badges: [{ kind: "sobmedida", label: "Projeto especial" }],
    rating: 5,
    ratingCount: 4,
    bulk: [{ qty: "Sob projeto", price: "Consulte" }],
    imageTone: "dark",
    image: "/products/mola-customizada.png",
    diameterWire: 0,
    specs: {
      dimensoes: [{ key: "Configuração", value: "Sob projeto" }],
      desempenho: [
        { key: "Prazo de orçamento", value: "Até 24h" },
        { key: "Documento exigido", value: "Desenho técnico ou amostra" },
      ],
    },
  },
];

export function getProduct(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getRelated(slug: string, n = 4): Product[] {
  const cur = getProduct(slug);
  if (!cur) return PRODUCTS.slice(0, n);
  return [
    ...PRODUCTS.filter((p) => p.category === cur.category && p.slug !== slug),
    ...PRODUCTS.filter((p) => p.category !== cur.category && p.slug !== slug),
  ].slice(0, n);
}
